### ISSUE TITLE
Backup script breaks on long backups

### ISSUE THREAD

**Issue by MrApe** [project-fifo/pyfi#19]
fifo-backup breaks if run on multiple bigger machines:

````
Traceback (most recent call last):
  File "/opt/local/bin/fifo", line 124, in <module>
    wiggle.init(host, user, pw, token, apiVersion, insecure)
  File "/opt/local/lib/python2.7/site-packages/fifo/api/wiggle.py", line 27, in init
    if not self.set_token(token):
  File "/opt/local/lib/python2.7/site-packages/fifo/api/wiggle.py", line 43, in set_token
    return self.get('sessions', token)
  File "/opt/local/lib/python2.7/site-packages/fifo/api/wiggle.py", line 50, in get
    conn.request('GET', self._apiEndpoint + resource + '/' + entity + suffix, '', hdrs)
  File "/opt/local/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/opt/local/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/opt/local/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/opt/local/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/opt/local/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/opt/local/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/opt/local/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/opt/local/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 146] Connection refused

**Comment by Licenser** [comment]
can you please re-open this on the jira and attach the howl logs?
